name: Fetch Manga

on:
  workflow_dispatch:
    inputs:
      page_range:
        description: 'Page range to fetch (e.g., 1-200)'
        required: true
        default: '401-600'
  schedule:
    - cron: '0 0 * * *'  

jobs:
  fetch:
    runs-on: ubuntu-latest
    
    # Add write permissions for the GITHUB_TOKEN
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Important for git history operations

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install node-fetch@2

    - name: Fetch AniList data
      run: node script/manga.js ${{ github.event.inputs.page_range || '1-401' }}

    - name: Commit and push changes
      run: |
        # Configure git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Stage, commit, and push
        git add data/manga-*.json
        git status
        git diff-index --quiet HEAD || git commit -m "Update AniList data ${{ github.event.inputs.page_range || '1-400' }}"
        git pull --rebase  # Ensure we're up to date
        git push
        
        # Verify push was successful
        echo "Changes pushed successfully"
